FORMAT: 1A
HOST: http://127.0.0.1:3000

# gtzompantzi

Polls is a simple API allowing consumers to view polls and vote in them.

## Metodo [/questions]

### Hola mundo [GET]

+ Response 200 (application/json)

        
            {
                "message": "Hola gtzompantzi"
            }